version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  ${rootArtifactId}-webapp:
    image: ${rootArtifactId}:latest
    ports:
      - 8080:8080
    depends_on:
      - db